### ISSUE TITLE
Highlight marks not visible from a title attribute and its natural tooltip

### ISSUE THREAD

**Issue by PBrockmann** [julmot/datatables.mark.js#15]
Is it possible to see highlight marks from a title attribut of a span html tag ?

The occurence is correctly found from 
`
<span title="This is a long long text">This...</span>
`
but the hightlight is not visible.

**Comment by julmot** [comment]
If you want to search for matches in an attribute you can use native selectors, you don't need mark.js for that.

**Comment by PBrockmann** [comment]
Hi, 

Off github issue. 

Sorry, perhaps I didn't explain the problem correctly. I try again. 

From a datatable with a search input, I would like to highlight 
any occurence found. This works for all occurence visible from the table 
but not the ones that have been shortered because the text was too long 
to be exposed and the all text still visible from the title attribut. 
<span title="This is a long long text">This...</span> 
The occurence is found but not highligted. 

So the problem is not the search but the fact that through a tooltip title, 
the occurence found is not marked (highlighted). 

Is there a solution to that ? 

Thanks 
Patrick Brockmann 


-- 
Data Analysis and Visualization Engineer 
Software Developper / Project Manager 
LSCE/IPSL, CEA-CNRS-UVSQ laboratory 
LSCE - Climate and Environment Sciences Laboratory 
IPSL - Institut Pierre Simon Laplace 
-- 


De: "Julian Kühnel" <notifications@github.com> 
À: "julmot/datatables.mark.js" <datatables.mark.js@noreply.github.com> 
Cc: "Patrick Brockmann" <Patrick.Brockmann@lsce.ipsl.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 24 Mai 2018 18:17:10 
Objet: Re: [julmot/datatables.mark.js] Highlight marks not visible from a title attribute and its natural tooltip (#15) 



If you want to search for matches in an attribute you can use native selectors, you don't need mark.js for that.

**Comment by PBrockmann** [comment]
I would expect a tootip with 'rabbit' highlighted if the search is on the word 'rabbit' event if this will appear only in the tooltip title.

**Comment by julmot** [comment]
You can not wrap things in an attribute... HTML is not allowed in attributes. So you will have to place the tooltip contents in an HTML element that you're able to highlight things.

**Comment by PBrockmann** [comment]
Do you have any exemple with this kind of request ?
A datatable with a shortened columns and a search feature that marks occurrence in a tooltip.

**Comment by PBrockmann** [comment]
Could you have a look to https://jsfiddle.net/PBrockmann/6594ak9f/ ?

When you search for 'tech', A 'System Architect' is found but the tooltip is not highlighted.
Note that I have used popper.js (tooltip.js) where tooptip can include HTML tags (data-html="true").

Any help welcome on this.

**Comment by julmot** [comment]
First of all, `$('[data-toggle="tooltip"]').tooltip()` will enable tooltips everywhere, not just in the drawing table. So this is a performance issue.

Then, you can use [this example](https://stackoverflow.com/a/34872134/3894981) to create a Bootstrap tooltip where the actual HTML is not located in the `title` attribute. Then, mark.js will also highlight matches in the tooltip content.

**Comment by PBrockmann** [comment]
Ok understood for your first remark.
On the second one, I have updated my JSFiddle with a tooltip outside the title attribut but it is not working as expected because the data tooltip are dynamically created I think.
Any idea ?

**Comment by julmot** [comment]
@PBrockmann This isn't what I meant. Have a look at this example:

https://jsfiddle.net/6594ak9f/9/

Basically you have two elements, one is the tip toggle that includes that truncated title and one is the tip content that includes the full content. Both are located in the table itself, so mark.js will mark matches in both contexts. But your tip initialization is still wrong. You're initializing it after DataTables but you'd have to initialize it after every DataTables draw event since you want to update the tip content where they may be marked words.

**Comment by PBrockmann** [comment]
Thanks again to interact on this issue.
I don't see any highlighted text in the tooltip when I type 'tec' for example.

**Comment by julmot** [comment]
Mate, I gave you tips on how to do this. I'm not your personal software developer that develops your use cases...

Something like this should do the trick: https://jsfiddle.net/6594ak9f/10/

Please ask questions that are off-topic on StackOverflow.

**Comment by PBrockmann** [comment]
Ok sure. 
Juste that this issue might be interesting to solve from the documentation.
Thank for your help.
