### ISSUE TITLE
Webpack module not found

### ISSUE THREAD

**Issue by nreynis** [julmot/datatables.mark.js#16]
When compiling using webpack a Module not found exception is raised:

```
Module not found: Error: Can't resolve 'markjs' in 'project\node_modules\datatables.mark.js\dist'
 @ ./node_modules/datatables.mark.js/dist/datatables.mark.js 23:4-25:6
```

This is due to this line:
https://github.com/julmot/datatables.mark.js/blob/master/dist/datatables.mark.js#L23

Which tries to import a module named `markjs` while in fact the correct module name is `mark.js` in NPM:

https://github.com/julmot/mark.js/blob/master/package.json#L2

**Comment by nreynis** [comment]
Just found this was already a known issue:
https://github.com/julmot/datatables.mark.js/issues/7

May I suggest you document this on markjs.io ?
Webpack is one of the most used bundler, having to search in issues (let alone closed one) to make it work is suboptimal.

**Comment by julmot** [comment]
@nreynis Sure, Webpack should be supported. Can you please provide a minimal .zip example?
