### ISSUE TITLE
combine datatables.mark.js with responsive?

### ISSUE THREAD

**Issue by BibleFarm** [julmot/datatables.mark.js#21]
Is is possible to have mark highlighting search results in datatables columns that are shown in responsive child rows?

I've modified your fiddle to make it easy to explore the possibility: https://jsfiddle.net/buh9h2r8/464/

Thanks!

**Comment by julmot** [comment]
Hi @alexbible,

Thanks for submitting.

As I can see, there's an element tr.child that is generated on the fly when resizing to a mobile viewport. Unfortunately, this element isn't available in Desktop viewports, therefore when highlighting in Desktop viewports and then switching to mobile viewports the highlighting disappears.

Sure, it would be possible to re-highlight on re-size, but the easiest option would be to always generate the tr.child element. Is there an option for that @DataTables that datatables.mark.js could trigger?

**Comment by DataTables** [comment]
[`responsive-display` is the event](https://datatables.net/reference/event/responsive-display) that you want here.

**Comment by alexbible** [comment]
Julian & Allan,

I think I'm at least going in the right direction.
Here's my updated fiddle: https://jsfiddle.net/buh9h2r8/514/

I appreciate your friendliness :)

**Comment by paulo-serrao** [comment]
It would be great to have this feature 👍
