### ISSUE TITLE
Diacritics

### ISSUE THREAD

**Issue by camoix** [julmot/datatables.mark.js#5]
Hi, seems that the search for diacritics, don't work properly, it don't ignore the diacritic search.

If you search for "chíef" on that sample https://jsfiddle.net/julmot/buh9h2r8/ have no results.

but if you search for "lórem" on that other https://jsfiddle.net/julmot/vpav6tL1/ highlights all the instances of "lorem"

in the options, the "diacritics": true, seems don't works well

datatables.min 1.10.12
DataTables Bootstrap 3
datatables.mark.js v2.0.0
jquery.mark.min.js v8.4.0

**Comment by julmot** [comment]
Hi @camoix,

Thanks for submitting.

Unfortunately I'm unable to reproduce any problem. There is no match for `chíef` on the page you've provided and that's the reason why nothing is highlighted. 

If you're confused about that no match is shown (not that no highlighting will be done) then [this page](https://datatables.net/plug-ins/filtering/type-based/accent-neutralise) describes how to find also matches that contain diacritics from a DataTables point of view. The `diacritics` option doesn't affect DataTables search behavior. The solution provided there isn't very comfortable but will hopefully be once the [diacritics project](http://diacritics.io) is set up and running.

If this isn't your problem please provide a fiddle with your real code using datatables.mark.js and I'd love to help you.

**Comment by camoix** [comment]
Hi Julmot, thanks a lot for your reply.
I made a fiddle to try to explain my confusion: https://jsfiddle.net/xesc/ymL66be9/10/
If you search for Doris, it find one match.
If you search for Dorís, it find one match.
I think, that any of these search, has to find 2 matches, Doris and Dorís, but maybe its a strict search.

But if you search just "is", it finds Dorís and Doris.

I don't understand the way it works.
Thanks for your time.

**Comment by julmot** [comment]
@camoix As mentioned you'll have to use the "Accent neutralise" plugin from DataTables as mark.js doesn't affect the actual search behavior of DataTables (what entries will be found). It just marks matches on already filtered rows.

Here's an example with the [above named plugin](//cdn.datatables.net/plug-ins/1.10.12/filtering/type-based/accent-neutralise.js): https://jsfiddle.net/ymL66be9/11/

Unfortunately this only works when entering "Doris", not when entering "Dorís". Anyway, this is something you should discuss with @DataTables e.g. in the [DataTables forum](https://datatables.net/forums/) as it's not related to mark.js or datatables.mark.js. Once the [diacritics project](http://diacritics.io/) is up and running I guess we can discuss about a better plugin.

Thanks for your understanding.

**Comment by camoix** [comment]
Ok, understood. Thanks for your time Julmot.
