### ISSUE TITLE
jquery 3

### ISSUE THREAD

**Issue by DiegoWtf** [julmot/datatables.mark.js#6]
I think it's not worked with jquery 3. https://jsfiddle.net/buh9h2r8/116/
Can you help me?

**Comment by julmot** [comment]
Hi @DiegoWtf,

Thanks for submitting.

Please have a look at your browser console:

![support](https://cloud.githubusercontent.com/assets/8310677/22327574/32b5e0d0-e3b8-11e6-83db-4eddb8c7de6a.png)

You need to embed jQuery using `https`, as [jsFiddle](http://jsfiddle.net) uses it. Here's the updated, working fiddle: https://jsfiddle.net/buh9h2r8/117/

**Comment by DiegoWtf** [comment]
Hm... Sorry. I think at jquery coz in my internal project i get this error:
![markjs_error1](https://cloud.githubusercontent.com/assets/8034654/22327917/b75ebbf6-e3ca-11e6-98ea-5ebbdddc2189.jpg)
And i still can't find what's wrong...

**Comment by julmot** [comment]
Hi @DiegoWtf,

If you have another problem, please create a new issue and provide the things named in [the contribution guidelines](https://github.com/julmot/datatables.mark.js/blob/master/CONTRIBUTING.md#11-questions-problems-and-bugs).
