### ISSUE TITLE
Table is drawn without the search input field

### ISSUE THREAD

**Issue by netmac** [julmot/datatables.mark.js#9]
I have a strange behavior where the table is drawn alone without the search input field, and without the show dropdown. I have to refresh (F5) many times before they show again. Then another refresh will make them again disappear.

### Steps to reproduce

The bug is not reproducible because the number of needed refresh is random.

As a test, I have added inside the DataTable() function, the following callback  : 

        // Initialize DataTables
        $('.datatables-table').DataTable({
            // Enable mark.js search term highlighting
            mark: true,
            "drawCallback": function( settings ) {
                alert( 'DataTables has redrawn the table' );
            },
        });

When the table is drawn alone without the search input field, the message 'DataTables has redrawn the table' does not show. Conversely, when the table is drawn with the search input field, the message 'DataTables has redrawn the table' does show.

### Environment

- Browser name and version : Chrome 60.0.3112.113
- jQuery version : 1.11.1
- DataTables version : 1.10.13
- mark.js version : 8.6.0
- datatables.mark.js version : 2.0.0

**Comment by julmot** [comment]
Hi @netmac,

Thanks for submitting.

I'd like to help you, but I can't without a [fiddle](http://jsfiddle.net) demonstrating the problem – as mentioned in the [issue template](https://github.com/julmot/datatables.mark.js/blob/master/ISSUE_TEMPLATE.md) as well as in the [contribution guideline](https://github.com/julmot/datatables.mark.js/blob/master/CONTRIBUTING.md).

The fiddle I've created based on the versions you've specified is successfully in the latest Chrome:

https://jsfiddle.net/buh9h2r8/166/

**Comment by netmac** [comment]
Thanks @julmot for the feedback.

Actually the issue was because the initialization code  $('.datatables-table').DataTable() was placed at the wrong place. It was executed while the actual table was not existing yet, as the table is sent within a partial view.

Now it is working. Thanks again,
